#!/bin/sh

if [ "$1" = 'liveness' ]; then
    gossfile=liveness.yaml
    port=8081
else
    gossfile=readiness.yaml
    port=8080
fi

set -- -g /goss/$gossfile serve -l ":$port" -f json "${@:2}"

exec goss "$@"
